import tkinter as tk
from tkinter import*
def color():
    if var.get()==0:
        root.configure(background="red")
        red.configure(background="red")
        green.configure(background="red")
        yellow.configure(background="red")
        blue.configure(background="red")
        purple.configure(background="red")
        ukr.configure(background="red")
        button.configure(background="white")
    elif var.get()==1:
        root.configure(background="green")
        red.configure(background="green")
        green.configure(background="green")
        yellow.configure(background="green")
        blue.configure(background="green")
        purple.configure(background="green")
        ukr.configure(background="green")
        button.configure(background="white")
    elif var.get()==2:
        root.configure(background="yellow")
        red.configure(background="yellow")
        green.configure(background="yellow")
        yellow.configure(background="yellow")
        blue.configure(background="yellow")
        purple.configure(background="yellow")
        ukr.configure(background="yellow")
        button.configure(background="white")
    elif var.get()==3:
        root.configure(background="blue")
        red.configure(background="blue")
        green.configure(background="blue")
        yellow.configure(background="blue")
        blue.configure(background="blue")
        purple.configure(background="blue")
        ukr.configure(background="blue")
        button.configure(background="white")
    elif var.get()==4:
        root.configure(background="purple")
        red.configure(background="purple")
        green.configure(background="purple")
        yellow.configure(background="purple")
        blue.configure(background="purple")
        purple.configure(background="purple")
        ukr.configure(background="purple")
        button.configure(background="white")
    elif var.get()==5:
        root.configure(background="yellow")
        red.configure(background="blue")
        green.configure(background="blue")
        yellow.configure(background="blue")
        blue.configure(background="blue")
        purple.configure(background="yellow")
        button.configure(background="yellow")
        ukr.configure(background="yellow")
root=tk.Tk()
root.resizable(False,False)
var=IntVar()
var.set(0)
red=Radiobutton(text="Червоний",variable=var,value=0, width="15")
green=Radiobutton(text="Зелений",variable=var,value=1, width="15")
yellow=Radiobutton(text="Жовтий",variable=var,value=2, width="15")
blue=Radiobutton(text="Синій",variable=var,value=3, width="15")
purple=Radiobutton(text="Фіолетовий",variable=var,value=4, width="15")
ukr=Radiobutton(text="Національний",variable=var,value=5, width="15")
button=Button(root, text="Змінити", font="Arial 10", command=color)
red.pack()
green.pack()
yellow.pack()
blue.pack()
purple.pack()
ukr.pack()
button.pack(pady="10")
root.mainloop()